### ISSUE TITLE
How can I get the complete data set in your paper

### ISSUE THREAD

**Issue by liuhuadong2018** [webis-de/unit-segmentation-of-argumentative-texts#1]

**Comment by YamenAjjour** [comment]
Hi, 
The datasets can be found here
Editorials: https://webis.de/data/webis-editorials-16.html
Essays: https://www.informatik.tu-darmstadt.de/ukp/research_6/data/argumentation_mining_1/argument_annotated_essays/index.en.jsp
Web Discourse: https://www.informatik.tu-darmstadt.de/ukp/research_6/data/argumentation_mining_1/argument_annotated_user_generated_web_discourse/index.en.jsp

You should extract the features lin the following format [0] in order to run our neural network
[0]: https://github.com/webis-de/ARGMINING-17/blob/master/sample_data/essay004.txt
Best,
Yamen
